<a href="https://colab.research.google.com/github/saxena431/Sareni2/blob/main/Sareni_Data_Making.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [105]:
import pandas as pd

In [106]:
df=pd.read_excel("/content/Try.xlsx")
df2=pd.read_excel("/content/Sareni_Calling_Code_INFO.xlsx")

In [107]:
df.head(1)

,OnlineSurveyId,ParliamentId,AssemblyId,WardId,BoothId,RespondentFirstName,RespondentSecondName,MobileNo1,MobileNo2,RelationName,...,Question51,Question52,Question53,Question54,Question55,SurveyStatus,SurveyorID,ClientId,CallResponse,SurvayDate
0,3077177,513,513182,5131828010,5131821460,Laxmi singh,1,7501807126,a,rupand Partap Singh,...,1,1,1,1,1,1,3564,458,No Call,2026-03-18 10:07:24.460

In [108]:
df.columns

Index(['OnlineSurveyId', 'ParliamentId', 'AssemblyId', 'WardId', 'BoothId',
       'RespondentFirstName', 'RespondentSecondName', 'MobileNo1', 'MobileNo2',
       'RelationName', 'MobileNo3', 'HouseNo', 'HouseHold', 'MaritalStatus',
       'IdType', 'IdNo', 'IdImage', 'ProfilePic', 'SocialMedia',
       'SocialMediaType', 'IncomeGroup', 'NativeState', 'Latitude',
       'Longitude', 'Question1', 'Question2', 'Question3', 'Question4',
       'Question5', 'Question6', 'Question7', 'Question8', 'Question9',
       'Question10', 'Question11', 'Question12', 'Question13', 'Question14',
       'Question15', 'Question16', 'Question17', 'Question18', 'Question19',
       'Question20', 'Question21', 'Question22', 'Question23', 'Question24',
       'Question25', 'Question26', 'Question27', 'Question28', 'Question29',
       'Question30', 'Question31', 'Question32', 'Question33', 'Question34',
       'Question35', 'Question36', 'Question37', 'Question38', 'Question39',
       'Question40', 'Question41', 'Question42', 'Question43', 'Question44',
       'Question45', 'Question46', 'Question47', 'Question48', 'Question49',
       'Question50', 'Question51', 'Question52', 'Question53', 'Question54',
       'Question55', 'SurveyStatus', 'SurveyorID', 'ClientId', 'CallResponse',
       'SurvayDate'],
      dtype='object')

In [109]:
df1 = pd.DataFrame({
    'name': df['SocialMedia'],
    'creation': df['Question35'],
    'Booth No': df['MobileNo3'],
    'Name': df['RespondentFirstName'],
    'Father Name': df['RelationName'],
    'Mobile No': df['MobileNo1'],
    'Age': df['Question1'],
    'Education': df['Question2'],
    'Gender': df['Question3'],
    'Occupation': df['Question4'],
    'Category': df['Question5'],
    'Caste': df['Question6'],
    'आप आने वाले विधानसभा चुनाव 2027 मे किस पार्टी को अपना वोट देना चाहेगें?': df['Question7'],
    'आप आने वाले विधानसभा चुनाव 2027 मे किस उम्मीदवार को अपना वोट देना चाहेगें?': df['Question8'],
    'निम्न में से कौन सी स्थानीय समस्या आपके दैनिक जीवन को सर्वाधिक प्रभावित करती है ?': df['Question9'],
    'आपके जिले में सबसे बड़ा मुद्दा क्या है ?': df['Question10'],
    'आप अपने वर्तमान विधायक के कार्यो से खुश हैं?': df['Question11'],
    'आपको किस राज्य सरकार का कार्यकाल ज्यादा अच्छा लगा ?': df['Question12'],
    'आप किन्हे उत्तर प्रदेश के अगले मुख्यमंत्री के रूप मे देखना चाहेंगे?': df['Question13']
})

In [110]:
df1.columns

Index(['name', 'creation', 'Booth No', 'Name', 'Father Name', 'Mobile No',
       'Age', 'Education', 'Gender', 'Occupation', 'Category', 'Caste',
       'आप आने वाले विधानसभा चुनाव 2027 मे किस पार्टी को अपना वोट देना चाहेगें?',
       'आप आने वाले विधानसभा चुनाव 2027 मे किस उम्मीदवार को अपना वोट देना चाहेगें?',
       'निम्न में से कौन सी स्थानीय समस्या आपके दैनिक जीवन को सर्वाधिक प्रभावित करती है ?',
       'आपके जिले में सबसे बड़ा मुद्दा क्या है ?',
       'आप अपने वर्तमान विधायक के कार्यो से खुश हैं?',
       'आपको किस राज्य सरकार का कार्यकाल ज्यादा अच्छा लगा ?',
       'आप किन्हे उत्तर प्रदेश के अगले मुख्यमंत्री के रूप मे देखना चाहेंगे?'],
      dtype='object')

In [111]:
id_to_name = dict(zip(df2['ID'], df2['Name']))

In [112]:
columns_to_convert = [
    'Education', 'Gender', 'Occupation', 'Category', 'Caste',
    'आप आने वाले विधानसभा चुनाव 2027 मे किस पार्टी को अपना वोट देना चाहेगें?',
    'आप आने वाले विधानसभा चुनाव 2027 मे किस उम्मीदवार को अपना वोट देना चाहेगें?',
    'निम्न में से कौन सी स्थानीय समस्या आपके दैनिक जीवन को सर्वाधिक प्रभावित करती है ?',
    'आपके जिले में सबसे बड़ा मुद्दा क्या है ?',
    'आप अपने वर्तमान विधायक के कार्यो से खुश हैं?',
    'आपको किस राज्य सरकार का कार्यकाल ज्यादा अच्छा लगा ?',
    'आप किन्हे उत्तर प्रदेश के अगले मुख्यमंत्री के रूप मे देखना चाहेंगे?'
]

In [113]:
for col in columns_to_convert:
    df1[col] = df1[col].map(id_to_name)

In [114]:
for col in columns_to_convert:
    df1[col] = df1[col].map(id_to_name).fillna(df1[col])

In [115]:
df1.head(5)

,name,creation,Booth No,Name,Father Name,Mobile No,Age,Education,Gender,Occupation,Category,Caste,आप आने वाले विधानसभा चुनाव 2027 मे किस पार्टी को अपना वोट देना चाहेगें?,आप आने वाले विधानसभा चुनाव 2027 मे किस उम्मीदवार को अपना वोट देना चाहेगें?,निम्न में से कौन सी स्थानीय समस्या आपके दैनिक जीवन को सर्वाधिक प्रभावित करती है ?,आपके जिले में सबसे बड़ा मुद्दा क्या है ?,आप अपने वर्तमान विधायक के कार्यो से खुश हैं?,आपको किस राज्य सरकार का कार्यकाल ज्यादा अच्छा लगा ?,आप किन्हे उत्तर प्रदेश के अगले मुख्यमंत्री के रूप मे देखना चाहेंगे?
0,bandeyi,2026-03-18 10:02:09,146,Laxmi singh,rupand Partap Singh,7501807126,42,12th,Male,Others,सामान्य,ठाकुर/राजपूत,BJP,धीरेन्द्र बहादुर सिंह - BJP,साफ.सफाई,खेतों की सिंचाई के लिए पानी,बिल्कुल नहीं,BJP- सरकार (योगी आदित्यनाथ ) (2017-Present),योगी आदित्यनाथ
1,beheta,2026-03-18 10:19:20,150,ashok,govardhan yadev,9021457066,39,10th,Male,Private Job,पिछड़ा,यादव,SP,देवेन्द्र प्रताप सिंह-SP,नाली,बेरोजगारी,कुछ कह नहीं सकते,SP- सरकार (अखिलेश यादव) (2012-2017),अखिलेश यादव
2,behata,2026-03-18 10:24:17,150,rajesh,vindadeen,6283422361,43,10th,Male,Farmers,पिछड़ा,यादव,SP,देवेन्द्र प्रताप सिंह-SP,नाली,बेरोजगारी,कुछ कह नहीं सकते,SP- सरकार (अखिलेश यादव) (2012-2017),अखिलेश यादव
3,behata,"Mar 18, 2026 10:28:18 AM",150,ramawati,awdhesh Kumar,9949920952,45,10th,Female,Farmers,पिछड़ा,यादव,SP,देवेन्द्र प्रताप सिंह-SP,पीने का पानी,बेरोजगारी,थोडा बहुत,SP- सरकार (अखिलेश यादव) (2012-2017),अखिलेश यादव
4,behata,2026-03-18 10:26:23,150,rajeshwari,asur deen,8168190325,60,10th,Female,Farmers,पिछड़ा,यादव,SP,Other,पीने का पानी,बेरोजगारी,थोडा बहुत,पता नहीं,अन्य

In [116]:
df1.to_excel("Sareni_Dataset_Call.xlsx")